### ISSUE TITLE
Inline Images

### ISSUE THREAD

**Issue by armaseg** [mailin-api/mailin-api-php#10]
I noticed that the API allows to send attachments, but I can't attach inline images. Doing some tests with your "Email campaign" section I saw that this is the way you add images to your mails.

I think it would be nice to add this feature to the Transactional Emails.

Thanks

**Comment by ekta-slit** [comment]
[Visit GitHub!](https://www.github.com)

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.

We have added new parameter 'inline_image' in Transactional Emails.
Please refer [Apidoc](https://apidocs.sendinblue.com/tutorial-sending-transactional-email/)

Regards,
Sendinblue Team
