### ISSUE TITLE
Email event reports in Campaign

### ISSUE THREAD

**Issue by armaseg** [mailin-api/mailin-api-php#11]
By now, is it possible to to get a really detailed report with "Email event reports" function in SMTP API. On the other hand, it isn't possible to get the same info from a Campaign since the report is handled directly from your site (mail with link). 

I think it would be nice to be able to have something like a "Campaign Email event reports" in order to be able to build customized reports.

Thanks in advance

**Comment by elmahdi** [comment]
Hello,

Thank you for contacting us.
We have well noted your idea but currently, we suggest you to use our webhook feature in order to achieve your aim and get a detailed report of your campaign's emails.

Regards,
Elmahdi from Sendinblue
