### ISSUE TITLE
curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

### ISSUE THREAD

**Issue by tplessis** [mailin-api/mailin-api-php#13]
Hi,

Everything is in the title : The option CURLOPT_FOLLOWLOCATION cannot be set when open_basedir is activated.

Maybe a solution here : 
http://php.net/manual/en/function.curl-setopt.php#95027

Regards,

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us and we are sorry for late reply.
You can remove `CURLOPT_FOLLOWLOCATION` from the wrapper or download our latest API V2 wrapper, which is up-to-date.

Regards,
SendinBlue Team

**Comment by roadster31** [comment]
When using composer, there is no way to tell the autoloader to use the V2 code located in the V2.0 directory, and this issue occurs again.

Deleting or manipulating library code is not a convenient solution, as the changes will be lost after an update.
