### ISSUE TITLE
It is not possible to use the http-headers for send_email()

### ISSUE THREAD

**Issue by slue** [mailin-api/mailin-api-php#14]
As stated in the api-docs (https://apidocs.sendinblue.com/tutorial-sending-transactional-email/) it is possible to set headers for transactional mails:
* X-Mailin-custom
* X-Mailin-IP
* X-Mailin-Tag

But I cannot set any headers in the mailin.php

thanks, christoph

**Comment by ekta-slit** [comment]
Hello Christoph,

Thank you for contacting us.

It is possible to set headers for transactional mails in _headers_ input parameter of send_email() api.
For example: 
`"headers" => array("Content-Type"=> "text/html; charset=iso-8859-1","X-param1"=> "value1", "X-param2"=> "value2","X-Mailin-custom"=>"my custom value", "X-Mailin-IP"=> "102.102.1.2", "X-Mailin-Tag" => "My tag"),`

Please refer the second sample [here](https://apidocs.sendinblue.com/tutorial-sending-transactional-email/)

Regards,
SendinBlue Team
