### ISSUE TITLE
Add option to specify message_id in get_report()

### ISSUE THREAD

**Issue by matbeard** [mailin-api/mailin-api-php#16]
It would be really handy to be able to retrieve a report for a specific message_id.

I'm trying to integrate the API into an app that easily allows users to see if a specific message has been opened (I store the message_id after sending transactional emails).

Any plans for this?

**Comment by pierrre** [comment]
Sorry for the late answer.
Please have a look at https://apidocs.sendinblue.com/report/ (and select the PHP example)
Is the `message_id` parameter what you need?
