### ISSUE TITLE
Add "IP address" parameter on create_update_user()

### ISSUE THREAD

**Issue by webaddicto** [mailin-api/mailin-api-php#19]
Would it be possible to include a new parameter "ip" on create_update_user()?

So I can include the user's IP address when I send emails to Sendinblue via a server script, else it is always logged the server's IP address in "Activity" tab.

Here is an example of how it can be:

```
$data = array( 
    "email" => $email,
    "listid" => array($listid),
    "ip" => $ip,
);
 
$output = $mailin->create_update_user($data);
```

Thank you.

**Comment by HJerem** [comment]
@webaddicto You can add custom attribute in SendInBlue admin panel named `ip` for example, then in your `$data` variable you set it like this:
```php
$data = array(
    "email" => $email,
    "listid" => array($listid),
    "attributes" => array(
        "ip" => $ip
    )
);
$output = $mailin->create_update_user($data);
```

**Comment by webaddicto** [comment]
Thank you for the answer, I will try that and report here if I find any issue.
