### ISSUE TITLE
Permissions on Sendinblue API

### ISSUE THREAD

**Issue by webaddicto** [mailin-api/mailin-api-php#22]
Hello,

Would it be possible to create a Sendinblue API and then set permissions on it?

For example, I want to create a Sendinblue API but I want to disable the following abilities:

- Export\import of emails
- Delete operations

What do you think about these additions?

Thank you.

**Comment by ekta-slit** [comment]
Hi @webaddicto 

Thanks for contacting us.
This facility is not available with SendinBlue APIs.

Regards
SendinBlue Team
