### ISSUE TITLE
RuntimeException not namespace properly - throws class not found error

### ISSUE THREAD

**Issue by wallyhall** [mailin-api/mailin-api-php#23]
There are references to `throw RuntimeException(...)` when curl calls fail, but the class is a PHP standard and is namespace outside the project.

There's a `use Exception` at the start of the file, but `RuntimeException` isn't resolvable via that.

**Comment by wallyhall** [comment]
See example fix in pull request #24

**Comment by Parvindersib** [comment]
Hello @wallyhall 

Thank you for contacting us.
We appreciate your suggestions and merged the PR.

Regards
SendinBlue Team
