### ISSUE TITLE
Contact transactional attributes not being updated

### ISSUE THREAD

**Issue by heyitsfranklin** [mailin-api/mailin-api-php#26]
Simple call:

```
$data = array( "email" => $order_email,
		"attributes" => array(
				"FIRST_NAME"=>$order_fname,
				"LAST_NAME"=>$order_lname,
				"PRODUCT"=>$service,
				"ORDER_ID"=>$order_id,
				"ORDER_DATE"=>$order->get_date_created()->__toString(),
				"ORDER_PRICE"=>$order->get_total()
				),
		"listid" => array($mailing_list_id)
);

$mailin->create_update_user($data);
```

Everytime a user completes an order on my website, I want that order info to be added to the transactional attributes I've set up (product, order_id, order_date, order_price). This only works the first time a user is added as a contact... every attempt thereafter (using the same user/contact email address) does not add another row to the contact's transactions.

I'm using v2 of the library.

**Comment by ekta-slit** [comment]
Hi @heyitsfranklin 

Can you please raise a support ticket here https://account.sendinblue.com/support with the details of the contact email address.
Our support team will revert you on this.

Thanks
