### ISSUE TITLE
What are the return parameters from send_email() function?

### ISSUE THREAD

**Issue by dennisbabkin** [mailin-api/mailin-api-php#28]
I'm reading [your documentation](https://apidocs.sendinblue.com/tutorial-sending-transactional-email/) for sending out transactional emails but I can't seem to find any documentation for the return parameters from send_email() function. I see that it returns an array, but what do its members mean? And how do I check if send_email() succeeded?

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-php-library
