### ISSUE TITLE
Lack of composer support

### ISSUE THREAD

**Issue by cagataygurturk** [mailin-api/mailin-api-php#4]
I think you should add composer support and one of PSR standards for autoloading.

**Comment by JMLamodiere** [comment]
+1 The "require" method to load the php class is very old school now. PHP community uses namespaces since PHP 5.3, and most open source libraries are now included using composer + packagist.org. It would help us a lot !
If you need help with that, just let me know, I would be glad to make a pull request. Could you just create an account on packagist.org and tell me the vendor name choosen (sendinblue or mailin ?)

**Comment by lokeshguptasldt** [comment]
@JMLamodiere we created account on packagist.org with username sendinblue

**Comment by Majstr** [comment]
So Will there be a composer support or should I look for a different mail provider‏?

**Comment by JMLamodiere** [comment]
@lokeshguptasldt Sorry I don't use this API anymore, and I had completely forgotten this issue. Could you take care of this ?

**Comment by lokeshguptasldt** [comment]
@Majstr @JMLamodiere yes we are working on this and will update shortly.

**Comment by lokeshguptasldt** [comment]
@Majstr @JMLamodiere Composer support is now available https://packagist.org/packages/mailin-api/mailin-api-php
Please let us know, if you face any issue.

**Comment by Majstr** [comment]
Not working. I thing the problem is in namespace. There is no namespace and you have 2 same files for V1 and V2.

**Comment by lokeshguptasldt** [comment]
@Majstr we are checking asap

**Comment by lokeshguptasldt** [comment]
@Majstr please try again. You should be able to use V2.0 api via composer.

**Comment by Majstr** [comment]
Noup. I get error "Class 'SendinBlue\Mailin' not found ". 
Problems might be in:
- file name is not the same as class
- wrong path for composer (autoload setting) -> my other vendors have paths set different
- 'throw new Exception('Mailin requires CURL module');' -> 'throw new \Exception('Mailin requires CURL module');'

**Comment by vansteen** [comment]
To follow the PSR-0 standard, the file mailin.php should be in a subfolder /mailin-api/mailin-api-php/V2.0/SendinBlue/. Then we'll not get the error: "Class 'SendinBlue\Mailin' not found "

**Comment by Majstr** [comment]
Now it's seem to work. Just fix 'Exception' to '\Exception'.

**Comment by lokeshguptasldt** [comment]
It should work now. Please check.

**Comment by HankBrown** [comment]
"Class 'SendinBlue\Mailin' not found"
using Yii2 framework.  Not a lot of experience with Yii2 yet, but every other composer package has installed ok.

I used:
composer require mailin-api/mailin-api-php dev-master

Now I am just guessing why this error occurs. All of these fail the same way.

```
        // SendinBlue
        'mailin' => [
            'class' => 'mailin-api\Sendinblue\Mailer',
            //'class'=>'vendor/mailin-api/mailin-api-php/src/Sendinblue/Mailin.php',
            //'class'=>'Sendinblue\Mailin'
        ],

```
My phpStorm IDE gives no clues, the namespaces seem to be okay.
But runtime blows up.
I don't suppose this is your problem, but if anyone can suggest how to get going...

**Comment by ekta-slit** [comment]
Hello @HankBrown 

Please refer here https://github.com/mailin-api/mailin-api-php/blob/master/src/Sendinblue/README.md for installation & quick start.
Hope the sample script helps you!

Thank you

**Comment by ChristianGiupponi** [comment]
I have the same issue, no namespace defined so I get `Class 'Sendinblue\Mailin' not found`
