### ISSUE TITLE
Add a List Transactional email (templates)

### ISSUE THREAD

**Issue by armaseg** [mailin-api/mailin-api-php#7]
By now, It's possible to Send a Template, Create a Template and Update a Template, but in order to send and update it's required to add the Template's id.

 I think it would be nice to have a way to list all Transactional email (templates) in order to get the template's id.

**Comment by elmahdi** [comment]
Hello,

Thank you for your message.
The function exists already (get_campaigns_v2()) and it was in "Campaign API" bloc.
We updated our doc to make the things more clear: https://apidocs.sendinblue.com/template/#4

**Comment by armaseg** [comment]
Thank you very much!
