### ISSUE TITLE
Include header in Send Transactional email (templates)

### ISSUE THREAD

**Issue by armaseg** [mailin-api/mailin-api-php#8]
By now, is it possible to add a mail header when we send a Transactional email (without templates)  so it's really useful to add tags and other custom fields.

$mailin->send_email($to,$subject,$from,$html,$text,$cc,$bcc,$replyto,$attachment,$headers)

I think it would be nice to add this option when we send Transactional email (templates)

**Comment by ekta-slit** [comment]
Hello,

Thank you for contacting us.

The option to send custom headers  is available now in Transactional email (templates).
Please refer our Apidoc here https://apidocs.sendinblue.com/template/#1

Regards,
SendinBlue Team
