### ISSUE TITLE
Standardize the Input Parameter to, cc, bcc between Sending transactional email and Sending transactional email (template)

### ISSUE THREAD

**Issue by armaseg** [mailin-api/mailin-api-php#9]
I think it would be nice to send parameters to this function in the same way, due to sending transactional emails without template it's require an array and with template is a string and is used a pipe ( | ) to separate multiple recipients.

**Comment by ekta-slit** [comment]
Hello,

Sorry for late reply & thank you for contacting us.

We appreciate your suggestions and will maintain the consistency within APIs in our next release version 3.0

Regards,
SendinBlue Team
